"""
Find document regions matching tagged examples using semantic kernel matching.

Builds a consensus kernel from all Tag records sharing a label, then slides
it across candidate pages' Word grids. Structural words (consistent text
across examples) are matched by text similarity; content words (varying text,
NER-labelled) are matched by entity type; all other slots use position only.

Examples::

    # Find matches in the same document as the source tags
    python manage.py match_tags --label "member entry"

    # Scope source tags to a specific document
    python manage.py match_tags --label "member entry" --source-document 3

    # Search a different target document
    python manage.py match_tags --label "member entry" --source-document 3 --target-document 5

    # Tune sensitivity
    python manage.py match_tags --label "member entry" --min-score 0.4 --tolerance 0.1

    # Auto-create Tag records for each match (for admin review)
    python manage.py match_tags --label "member entry" --source-document 3 --create-tags
"""

from django.contrib.contenttypes.models import ContentType
from django.core.management.base import BaseCommand, CommandError

from grime.pipeline.tag_match import build_kernel, search_page
from grime.models import Document, DocumentPage, Tag, Word


class Command(BaseCommand):
    help = "Find document regions matching tagged examples using semantic kernel matching."

    def add_arguments(self, parser):
        parser.add_argument("--label", required=True, metavar="LABEL", help="Tag label to match")
        parser.add_argument(
            "--source-document",
            metavar="ID",
            help="Restrict source tags to this document (pk or document_id)",
        )
        parser.add_argument(
            "--target-document",
            metavar="ID",
            help=("Search this document for matches (default: same document as source tags)"),
        )
        parser.add_argument(
            "--min-score",
            type=float,
            default=0.5,
            metavar="SCORE",
            help="Minimum match score to report (default: 0.5)",
        )
        parser.add_argument(
            "--tolerance",
            type=float,
            default=0.08,
            metavar="FRAC",
            help="Position tolerance as a fraction of the tag bbox size (default: 0.08)",
        )
        parser.add_argument(
            "--create-tags",
            action="store_true",
            help="Auto-create Tag records for each match with inferred subcomponents",
        )
        parser.add_argument(
            "--force",
            action="store_true",
            help="Re-create autogenerated tags that overlap matches (never overwrites manual tags)",
        )
        parser.add_argument(
            "--allow-overlaps",
            action="store_true",
            help="Create a tag for every match even if it overlaps another match in this run",
        )
        parser.add_argument(
            "--fields",
            metavar="LABELS",
            help="Comma-separated list of subcomponent labels to print (e.g. name,address)",
        )
        parser.add_argument(
            "-p",
            "--page",
            type=int,
            metavar="PAGE",
            help="Restrict search to this page number only",
        )
        parser.add_argument(
            "--video",
            metavar="OUTPUT_PATH",
            help="Save a convolution visualisation video to this path (e.g. match.mp4)",
        )
        parser.add_argument(
            "--video-fps",
            type=int,
            default=10,
            metavar="FPS",
            help="Frames per second for the output video (default: 10)",
        )
        parser.add_argument(
            "--print-matrix",
            action="store_true",
            help="Print the line-rank text matrix for each page (for debugging)",
        )

    def handle(self, **options):
        label = options["label"]
        min_score = options["min_score"]
        tolerance = options["tolerance"]
        video_path = options["video"]
        video_fps = options["video_fps"]
        create_tags = options["create_tags"]
        force = options["force"]
        allow_overlaps = options["allow_overlaps"]
        print_fields = (
            {f.strip() for f in options["fields"].split(",")} if options["fields"] else None
        )

        # -- Load source tags ------------------------------------------------
        source_tags_qs = Tag.objects.filter(label=label, created_by__isnull=False)
        if options["source_document"]:
            source_doc = self._resolve_document(options["source_document"])
            page_ct = ContentType.objects.get_for_model(DocumentPage)
            page_pks = list(source_doc.pages.values_list("pk", flat=True))
            source_tags_qs = source_tags_qs.filter(source_type=page_ct, source_id__in=page_pks)
        source_tags = list(source_tags_qs)
        if not source_tags:
            raise CommandError(
                f"No tags found with label '{label}'"
                + (
                    f" in document '{options['source_document']}'"
                    if options["source_document"]
                    else ""
                )
                + "."
            )
        self.stdout.write(f"Found {len(source_tags)} source tag(s) with label '{label}'.")

        # -- Build kernel ----------------------------------------------------
        kernel = build_kernel(source_tags)
        if not kernel:
            raise CommandError("Could not build kernel — source tags have no subcomponent words.")
        self.stdout.write(
            f"Kernel: {len(kernel)} slots ({sum(1 for s in kernel if s['slot_type']=='structural')} structural, "
            f"{sum(1 for s in kernel if s['slot_type']=='content')} content, "
            f"{sum(1 for s in kernel if s['slot_type']=='position')} position-only)"
        )

        # Reference bbox dimensions (median across source tags)
        import statistics

        ref_w = int(statistics.median(t.bbox_width for t in source_tags))
        ref_h = int(statistics.median(t.bbox_height for t in source_tags))

        # -- Resolve target document -----------------------------------------
        if options["target_document"]:
            target_doc = self._resolve_document(options["target_document"])
        else:
            # Infer target document from source tags
            page_ct = ContentType.objects.get_for_model(DocumentPage)
            source_page_ids = [
                t.source_id
                for t in source_tags
                if t.source_type == page_ct
                or (hasattr(t, "source_type") and t.source_type_id == page_ct.id)
            ]
            if not source_page_ids:
                raise CommandError(
                    "Source tags are not on DocumentPage records. "
                    "Use --target-document to specify a search target."
                )
            first_page = DocumentPage.objects.filter(pk__in=source_page_ids).first()
            if not first_page:
                raise CommandError("Could not resolve source document from tags.")
            target_doc = first_page.document

        pages_qs = target_doc.pages.order_by("page_number")
        if options["page"] is not None:
            pages_qs = pages_qs.filter(page_number=options["page"])
        pages = list(pages_qs)
        if not pages:
            raise CommandError(
                f"Document '{target_doc}' has no pages"
                + (f" with page_number={options['page']}" if options["page"] is not None else "")
                + "."
            )
        self.stdout.write(f"Searching {len(pages)} page(s) in '{target_doc}'…\n")

        page_ct = ContentType.objects.get_for_model(DocumentPage)
        total_matches = 0
        created_count = 0
        skipped_manual = 0
        video_frames = [] if video_path else None

        # With --force, wipe all autogenerated tags for this label in the document upfront.
        if create_tags and force:
            deleted, _ = Tag.objects.filter(
                source_type=page_ct,
                label=label,
                source_id__in=[p.pk for p in pages],
                created_by=None,
            ).delete()
            if deleted:
                self.stdout.write(f"Deleted {deleted} existing autogenerated tag(s).\n")

        # Index remaining tags for this label by page pk for overlap checking.
        existing_by_page: dict[int, list] = {}
        for t in Tag.objects.filter(
            source_type=page_ct, label=label, source_id__in=[p.pk for p in pages]
        ):
            existing_by_page.setdefault(t.source_id, []).append(t)

        for page in pages:
            page_words = list(
                Word.objects.filter(page=page)
                .order_by("block_num", "par_num", "line_num", "word_num")
                .values(
                    "id",
                    "left",
                    "top",
                    "width",
                    "height",
                    "text",
                    "corrected_text",
                    "ner_label",
                    "corrected_ner_label",
                    "block_num",
                    "par_num",
                    "line_num",
                    "word_num",
                )
            )
            if not page_words:
                continue

            if options["print_matrix"]:
                from grime.pipeline.tag_match import _assign_line_ranks
                import statistics as _stats

                page_label = (
                    f"p.{page.page_number:04d}" if page.page_number is not None else str(page)
                )
                self.stdout.write(f"\n── Matrix: {page_label} ({len(page_words)} words) ──")
                lines = _assign_line_ranks(list(page_words))
                for lr, line_words in enumerate(lines):
                    mid_y = int(_stats.median(w["top"] + w["height"] / 2 for w in line_words))
                    sorted_words = sorted(line_words, key=lambda w: w["left"])
                    tokens = [w.get("corrected_text") or w.get("text") or "" for w in sorted_words]
                    self.stdout.write(f"  [{lr:3d}] y≈{mid_y:4d}  {' '.join(tokens)}")
                self.stdout.write("")

            step_callback = None
            if video_frames is not None:
                from PIL import Image as PilImage
                from grime.pipeline.tag_viz import render_frame

                page_img = None
                if page.image:
                    try:
                        page_img = PilImage.open(page.image.path)
                    except Exception:
                        pass

                def step_callback(
                    bbox_left,
                    bbox_top,
                    score,
                    matched_slots,
                    _img=page_img,
                    _words=page_words,
                    _k=kernel,
                    _rw=ref_w,
                    _rh=ref_h,
                ):
                    video_frames.append(
                        render_frame(
                            _img, _words, _k, matched_slots, bbox_left, bbox_top, _rw, _rh, score
                        )
                    )

            matches = search_page(
                kernel,
                page_words,
                tolerance=tolerance,
                min_score=min_score,
                step_callback=step_callback,
            )
            if not matches:
                continue

            page_label = f"p.{page.page_number:04d}" if page.page_number is not None else str(page)
            existing_tags = existing_by_page.setdefault(page.pk, [])
            created_this_run: set[int] = set()
            for m in matches:
                total_matches += 1
                if print_fields:
                    fields_str = "  ".join(
                        f"{sc['label']}={sc['text']!r}"
                        for sc in m["inferred_subcomponents"]
                        if sc["label"] in print_fields
                    )
                else:
                    fields_str = ""
                line = f"  {page_label}  ({m['left']}, {m['top']})  score={m['score']:.2f}" + (
                    f"  [{fields_str}]" if fields_str else ""
                )
                m_right = m["left"] + ref_w
                m_bottom = m["top"] + ref_h
                overlapping = [
                    t
                    for t in existing_tags
                    if not (
                        m_right < t.bbox_left
                        or m["left"] > t.bbox_left + t.bbox_width
                        or m_bottom < t.bbox_top
                        or m["top"] > t.bbox_top + t.bbox_height
                    )
                ]
                preexisting_overlap = [t for t in overlapping if t.pk not in created_this_run]
                samerun_overlap = [t for t in overlapping if t.pk in created_this_run]
                has_manual_overlap = any(not t.autogenerated for t in preexisting_overlap)
                has_auto_overlap = any(t.autogenerated for t in preexisting_overlap)
                if preexisting_overlap:
                    self.stdout.write(self.style.WARNING(line))
                elif samerun_overlap and not allow_overlaps:
                    self.stdout.write(
                        self.style.SUCCESS(line + "  (overlaps match above, skipped)")
                    )
                else:
                    self.stdout.write(line)

                if create_tags:
                    if has_manual_overlap:
                        skipped_manual += 1
                    elif has_auto_overlap:
                        pass  # already exists; --force cleared these upfront
                    elif samerun_overlap and not allow_overlaps:
                        pass  # overlaps a tag created earlier in this run
                    else:
                        left = max(0, m["left"])
                        top = max(0, m["top"])
                        new_tag = Tag.objects.create(
                            source_type=page_ct,
                            source_id=page.pk,
                            label=label,
                            bbox_left=left,
                            bbox_top=top,
                            bbox_width=ref_w,
                            bbox_height=ref_h,
                            subcomponents=[
                                {
                                    "word_id": w["id"],
                                    "label": sc["label"],
                                    "text": w.get("corrected_text") or w.get("text") or "",
                                }
                                for sc in m["inferred_subcomponents"]
                                for w in sc.get("words", [])
                            ],
                        )
                        existing_tags.append(new_tag)
                        created_this_run.add(new_tag.pk)
                        created_count += 1

        if video_frames is not None:
            if video_frames:
                from grime.pipeline.tag_viz import frames_to_video

                self.stdout.write(f"\nRendering {len(video_frames)} frame(s) → '{video_path}'…")
                frames_to_video(video_frames, video_path, fps=video_fps)
                self.stdout.write(self.style.SUCCESS(f"Video saved → {video_path}"))
            else:
                self.stdout.write(self.style.WARNING("No frames captured (no anchor words found)."))

        if total_matches == 0:
            self.stdout.write(self.style.WARNING("No matches found."))
        else:
            summary = f"\nFound {total_matches} match(es) above score {min_score}."
            if create_tags:
                summary += f" Created {created_count} Tag record(s)."
                if skipped_manual:
                    summary += f" Skipped {skipped_manual} (overlap with manual tag)."
            self.stdout.write(self.style.SUCCESS(summary))

    def _resolve_document(self, id_arg: str) -> Document:
        doc = None
        if id_arg.isdigit():
            doc = Document.objects.filter(pk=int(id_arg)).first()
        if doc is None:
            doc = Document.objects.filter(document_id=id_arg).first()
        if doc is None:
            raise CommandError(f"Document '{id_arg}' not found.")
        return doc
