"""
Admin registrations for the grime document management app.

The DocumentPage change form embeds an inline document viewer that overlays
Word bboxes and Tag rectangles on the page image and lets users edit them.
Endpoint routing and JSON request handling live in ``grime.viewer``.
"""

from django.contrib import admin

from grime import viewer
from grime.models import Document, DocumentPage, NERPass, OCRPass, Tag, Word


class DocumentPageInline(admin.TabularInline):
    model = DocumentPage
    fields = ("page_number", "title", "text_complete", "text_source", "handwritten")
    readonly_fields = ("text_complete",)
    extra = 0
    show_change_link = True
    ordering = ("page_number",)


@admin.register(Document)
class DocumentAdmin(admin.ModelAdmin):
    list_display = (
        "title",
        "document_id",
        "page_count",
        "text_complete",
        "is_structured",
    )
    list_filter = ("text_complete", "is_structured", "handwritten")
    search_fields = ("title", "document_id")
    readonly_fields = ("page_count",)
    inlines = [DocumentPageInline]
    fieldsets = (
        (None, {"fields": ("title", "document_id", "url", "file")}),
        (
            "Content",
            {
                "fields": (
                    "text",
                    "text_complete",
                    "text_source",
                    "handwritten",
                    "manually_flagged",
                )
            },
        ),
        (
            "Structured",
            {"fields": ("is_structured", "column_schema"), "classes": ("collapse",)},
        ),
        ("Notes", {"fields": ("notes",), "classes": ("collapse",)}),
    )

    @admin.display(description="Pages")
    def page_count(self, obj):
        return obj.pages.count()


class WordInline(admin.TabularInline):
    model = Word
    fields = (
        "line_num",
        "word_num",
        "text",
        "corrected_text",
        "conf",
        "ner_label",
        "corrected_ner_label",
    )
    readonly_fields = ("line_num", "word_num", "text", "conf", "ner_label")
    extra = 0
    can_delete = False
    max_num = 0
    ordering = ("line_num", "word_num")

    def has_add_permission(self, request, obj=None):
        return False


# @admin.register(DocumentPage)
class DocumentPageAdmin(admin.ModelAdmin):
    list_display = (
        "__str__",
        "document",
        "page_number",
        "text_complete",
        "latest_ocr_method",
    )
    list_filter = ("text_complete", "text_source", "handwritten")
    search_fields = ("document__title", "title", "document_id")
    raw_id_fields = ("document",)
    inlines = [WordInline]
    change_form_template = "admin/grime/documentpage/change_form.html"
    fieldsets = (
        (None, {"fields": ("document", "page_number", "title", "file", "image")}),
        (
            "Content",
            {
                "fields": (
                    "text",
                    "text_complete",
                    "text_source",
                    "handwritten",
                )
            },
        ),
        (
            "Structured",
            {"fields": ("structured_data",), "classes": ("collapse",)},
        ),
        ("Notes", {"fields": ("notes",), "classes": ("collapse",)}),
    )

    @admin.display(description="OCR method")
    def latest_ocr_method(self, obj):
        latest = obj.ocr_passes.first()
        return latest.method if latest else "—"

    def get_urls(self):
        return super().get_urls()

    def change_view(self, request, object_id, form_url="", extra_context=None):
        extra_context = dict(extra_context or {})
        page = DocumentPage.objects.filter(pk=object_id).first()
        if page is not None:
            extra_context.update(viewer.build_viewer_context(page))
        return super().change_view(
            request, object_id, form_url, extra_context=extra_context
        )


# @admin.register(Word)
class WordAdmin(admin.ModelAdmin):
    list_display = ("__str__", "page", "line_num", "word_num", "conf", "ner_label")
    list_filter = ("ner_label", "is_ditto")
    search_fields = ("text", "corrected_text", "page__document__title")
    raw_id_fields = ("page", "ocr_pass", "ner_pass", "corrected_by", "corrected_ner_by")


@admin.register(Tag)
class TagAdmin(admin.ModelAdmin):
    list_display = ("label", "source", "autogenerated", "created_by", "created_at")
    list_filter = ("label", "created_by")
    search_fields = ("label",)
    readonly_fields = ("source", "subcomponents", "created_at")
    raw_id_fields = ("created_by",)

    @admin.display(boolean=True, description="Auto")
    def autogenerated(self, obj):
        return obj.autogenerated


# @admin.register(OCRPass)
class OCRPassAdmin(admin.ModelAdmin):
    list_display = ("__str__", "page", "method", "status", "confidence", "created_at")
    list_filter = ("method", "status")
    search_fields = ("page__document__title",)
    raw_id_fields = ("page",)
    readonly_fields = ("created_at", "output_text")


# @admin.register(NERPass)
class NERPassAdmin(admin.ModelAdmin):
    list_display = (
        "__str__",
        "page",
        "schema_name",
        "method",
        "status",
        "confidence",
        "threshold",
        "created_at",
    )
    list_filter = ("schema_name", "method", "status")
    search_fields = ("page__document__title",)
    raw_id_fields = ("page",)
    readonly_fields = ("created_at",)
