# Generated by Django 5.2.14 on 2026-05-14 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("document_id", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True)),
                ("text", models.TextField(blank=True)),
                ("text_complete", models.BooleanField(default=False)),
                (
                    "text_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ocr", "OCR"),
                            ("embedded", "Embedded"),
                            ("manual", "Manual"),
                        ],
                        help_text="How the text field was populated; set at ingest and not changed automatically",
                        max_length=20,
                    ),
                ),
                (
                    "handwritten",
                    models.BooleanField(
                        default=False,
                        help_text="Document is handwritten rather than typeset",
                    ),
                ),
                (
                    "manually_flagged",
                    models.BooleanField(
                        default=False, help_text="Manually flagged for follow-up"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "is_structured",
                    models.BooleanField(
                        default=False,
                        help_text="Pages contain tabular data; structured_data is extracted per page",
                    ),
                ),
                (
                    "column_schema",
                    models.JSONField(
                        blank=True,
                        help_text="Ordered list of column names for structured documents (e.g. ['name', 'address'])",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=1000)),
                ("url", models.URLField(blank=True)),
                ("text", models.TextField(blank=True)),
                ("text_complete", models.BooleanField(default=False)),
                (
                    "text_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ocr", "OCR"),
                            ("embedded", "Embedded"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("handwritten", models.BooleanField(default=False)),
                ("manually_flagged", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="document_pages/"
                    ),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True,
                        help_text="Table rows extracted from this page; list of dicts keyed by Document.column_schema",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="grime.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "page_number"],
            },
        ),
        migrations.CreateModel(
            name="NERPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        blank=True,
                        help_text="Template or schema used (e.g. 'hf-historical-ner')",
                        max_length=100,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="complete",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("used_llm", models.BooleanField(default=False)),
                ("llm_model", models.CharField(blank=True, max_length=100)),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ner_passes",
                        to="grime.documentpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "NER pass",
                "verbose_name_plural": "NER passes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OCRPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="Tool used, e.g. 'tesseract', 'textract'",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="complete",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Mean confidence for the page (0.0–100.0)",
                        null=True,
                    ),
                ),
                ("output_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_passes",
                        to="grime.documentpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR pass",
                "verbose_name_plural": "OCR passes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=200)),
                ("bbox_left", models.PositiveIntegerField()),
                ("bbox_top", models.PositiveIntegerField()),
                ("bbox_width", models.PositiveIntegerField()),
                ("bbox_height", models.PositiveIntegerField()),
                (
                    "subcomponents",
                    models.JSONField(
                        default=list,
                        help_text="[{word_id, label, text}, ...] — word-level sub-annotations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="grime_tag_source__71b2ef_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_num", models.PositiveSmallIntegerField(default=0)),
                ("par_num", models.PositiveSmallIntegerField(default=0)),
                ("line_num", models.PositiveSmallIntegerField()),
                ("word_num", models.PositiveSmallIntegerField()),
                ("left", models.PositiveIntegerField()),
                ("top", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("conf", models.FloatField(help_text="Per-word confidence (0–100)")),
                ("text", models.CharField(max_length=500)),
                (
                    "corrected_text",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_ditto", models.BooleanField(default=False)),
                ("corrected_ocr_at", models.DateTimeField(blank=True, null=True)),
                ("ner_label", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "corrected_ner_label",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("corrected_ner_at", models.DateTimeField(blank=True, null=True)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "corrected_ner_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ner_pass",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which NER run produced ner_label",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="words",
                        to="grime.nerpass",
                    ),
                ),
                (
                    "ocr_pass",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which OCR run produced this word",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="words",
                        to="grime.ocrpass",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="grime.documentpage",
                    ),
                ),
            ],
            options={
                "ordering": ["block_num", "par_num", "line_num", "word_num"],
                "unique_together": {
                    ("page", "block_num", "par_num", "line_num", "word_num")
                },
            },
        ),
    ]
