# Generated by Django 5.2.14 on 2026-05-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grime", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={"ordering": ["line_num", "word_num"]},
        ),
        migrations.RemoveField(
            model_name="document",
            name="column_schema",
        ),
        migrations.RemoveField(
            model_name="document",
            name="handwritten",
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_structured",
        ),
        migrations.RemoveField(
            model_name="document",
            name="text_complete",
        ),
        migrations.RemoveField(
            model_name="documentpage",
            name="handwritten",
        ),
        migrations.RemoveField(
            model_name="documentpage",
            name="structured_data",
        ),
        migrations.RemoveField(
            model_name="documentpage",
            name="text_complete",
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("page", "line_num", "word_num")},
        ),
        migrations.RemoveField(
            model_name="word",
            name="block_num",
        ),
        migrations.RemoveField(
            model_name="word",
            name="par_num",
        ),
    ]
