# Generated by Django 5.2.14 on 2026-05-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grime", "0002_alter_word_options_remove_document_column_schema_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="corrected_ner_label",
            new_name="corrected_label",
        ),
        migrations.RenameField(
            model_name="word",
            old_name="corrected_by",
            new_name="corrected_ocr_by",
        ),
        migrations.RenameField(
            model_name="word",
            old_name="text",
            new_name="ocr_text",
        ),
    ]
